plex:
  image: michaelcoll/armhf-plex
  ports:
    - "32400:32400"
  volumes:
    - "/net/nfs/video:/media"
    - "/net/nfs/photos:/photos"
    - "/net/nfs/config/plex:/config"
  net: "host"
sonarr:
  image: michaelcoll/armhf-sonarr 
  ports:
    - "8989:8989"
    - "9898:9898"
  volumes:
    - "/net/nfs/video:/volumes/media"
    - "/net/nfs/downloads:/volumes/completed"
    - "/net/nfs/config/sonarr:/volumes/config"
